/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Gabriel
 */
public class Cedula extends javax.swing.JPanel {

    /**
     * Creates new form Cedula
     */
    public Cedula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbCiudadano = new javax.swing.JRadioButton();
        rbIndigena = new javax.swing.JRadioButton();
        rbInmigrante = new javax.swing.JRadioButton();
        rbRefugiado = new javax.swing.JRadioButton();
        cCiudadano = new javax.swing.JTextField();
        cIndigena = new javax.swing.JTextField();
        cInmigrante = new javax.swing.JTextField();
        cRefugiado = new javax.swing.JTextField();
        lCiudadano = new javax.swing.JTextField();
        lIndigena = new javax.swing.JTextField();
        lInmigrante = new javax.swing.JTextField();
        lRefugiado = new javax.swing.JTextField();
        jlCedula = new javax.swing.JLabel();
        jlLugar = new javax.swing.JLabel();

        buttonGroup1.add(rbCiudadano);
        buttonGroup1.add(rbIndigena);
        buttonGroup1.add(rbInmigrante);
        buttonGroup1.add(rbRefugiado);

        rbCiudadano.setText("Ciudadano");
        rbCiudadano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbCiudadanoItemStateChanged(evt);
            }
        });
        rbCiudadano.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbCiudadanoStateChanged(evt);
            }
        });

        rbIndigena.setText("Indigena");
        rbIndigena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbIndigenaItemStateChanged(evt);
            }
        });

        rbInmigrante.setText("Inmigrante");
        rbInmigrante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbInmigranteItemStateChanged(evt);
            }
        });

        rbRefugiado.setText("Refugiado");
        rbRefugiado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbRefugiadoItemStateChanged(evt);
            }
        });

        cCiudadano.setEditable(false);

        cIndigena.setEditable(false);

        cInmigrante.setEditable(false);

        cRefugiado.setEditable(false);
        cRefugiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRefugiadoActionPerformed(evt);
            }
        });

        lCiudadano.setEditable(false);
        lCiudadano.setText("Nacional");

        lIndigena.setEditable(false);

        lInmigrante.setEditable(false);

        lRefugiado.setEditable(false);
        lRefugiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lRefugiadoActionPerformed(evt);
            }
        });

        jlCedula.setText("Cédula");

        jlLugar.setText("Lugar de Procedencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbIndigena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cIndigena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbInmigrante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cInmigrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbRefugiado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cRefugiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCiudadano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCedula)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIndigena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lInmigrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRefugiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLugar)
                    .addComponent(lCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbCiudadano, rbIndigena, rbInmigrante, rbRefugiado});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cCiudadano, cIndigena, cInmigrante, cRefugiado});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lCiudadano, lIndigena, lInmigrante, lRefugiado});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCedula)
                    .addComponent(jlLugar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCiudadano)
                    .addComponent(cCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIndigena)
                    .addComponent(cIndigena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIndigena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbInmigrante)
                    .addComponent(cInmigrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lInmigrante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRefugiado)
                    .addComponent(cRefugiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRefugiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cRefugiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRefugiadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cRefugiadoActionPerformed

    private void lRefugiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lRefugiadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lRefugiadoActionPerformed

    private void rbCiudadanoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbCiudadanoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCiudadanoStateChanged

    private void rbCiudadanoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbCiudadanoItemStateChanged
        modificarEstado();// TODO add your handling code here:
    }//GEN-LAST:event_rbCiudadanoItemStateChanged

    private void rbIndigenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbIndigenaItemStateChanged
        modificarEstado();        // TODO add your handling code here:
    }//GEN-LAST:event_rbIndigenaItemStateChanged

    private void rbInmigranteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbInmigranteItemStateChanged
       modificarEstado();
    }//GEN-LAST:event_rbInmigranteItemStateChanged

    private void rbRefugiadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbRefugiadoItemStateChanged
        modificarEstado();
    }//GEN-LAST:event_rbRefugiadoItemStateChanged
    public String getCedula()
    {
        String cedula="";
        if(rbCiudadano.isSelected()==true){
            cedula=cCiudadano.getText();
        }
        if(rbIndigena.isSelected()==true){
            cedula=cIndigena.getText();
        }
        if(rbInmigrante.isSelected()==true){
            cedula=cInmigrante.getText();
        }
        if(rbRefugiado.isSelected()==true){
            cedula=cRefugiado.getText();
        }
        return cedula;
    }
     public String getLocalizacion()
    {
        String localizacion="";
        if(rbCiudadano.isSelected()==true){
            localizacion=lCiudadano.getText();
        }
        if(rbIndigena.isSelected()==true){
            localizacion=lIndigena.getText();
        }
        if(rbInmigrante.isSelected()==true){
            localizacion=lInmigrante.getText();
        }
        if(rbRefugiado.isSelected()==true){
            localizacion=lRefugiado.getText();
        }
        return localizacion;
    }
    public void modificarEstado(){
    if(rbCiudadano.isSelected()==true){
        cCiudadano.setEditable(true);
    }else{
        cCiudadano.setEditable(false);
    }if(rbIndigena.isSelected()==true){
        cIndigena.setEditable(true);
        lIndigena.setEditable(true);
    }else{
        cIndigena.setEditable(false);
        lIndigena.setEditable(false);
    }if(rbInmigrante.isSelected()==true){
        cInmigrante.setEditable(true);
        lInmigrante.setEditable(true);
    }else{
        cInmigrante.setEditable(false);
        lInmigrante.setEditable(false);
    }if(rbRefugiado.isSelected()==true){
        cRefugiado.setEditable(true);
        lRefugiado.setEditable(true);
    }else{
        cRefugiado.setEditable(false);
        lRefugiado.setEditable(false);
    }
    }
    public void datos(Object Persona)
    {
        
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cCiudadano;
    private javax.swing.JTextField cIndigena;
    private javax.swing.JTextField cInmigrante;
    private javax.swing.JTextField cRefugiado;
    private javax.swing.JLabel jlCedula;
    private javax.swing.JLabel jlLugar;
    private javax.swing.JTextField lCiudadano;
    private javax.swing.JTextField lIndigena;
    private javax.swing.JTextField lInmigrante;
    private javax.swing.JTextField lRefugiado;
    private javax.swing.JRadioButton rbCiudadano;
    private javax.swing.JRadioButton rbIndigena;
    private javax.swing.JRadioButton rbInmigrante;
    private javax.swing.JRadioButton rbRefugiado;
    // End of variables declaration//GEN-END:variables
}
